# Site settings
site: Dhammapada Atthakatha
title: Dhammapada Atthakatha
description: Kisah-kisah Dhammapada
baseurl: "/Dhammapada-Atthakatha"
url: "http://anestan.github.io/Dhammapada-Atthakatha/" # the base hostname & protocol for your site
permalink: pretty
gems:
  - jekyll-seo-tag
google_analytics: UA-44222473-2
sass:
  sass_dir: _sass
  style: compressed
collections:
  yamaka_vagga:
    output: true
    title: Bab I - Yamaka Vagga
    description: Syair Berpasangan
    parent: /yamaka_vagga
  appamada_vagga:
    output: true
    title: Bab II - Appamada Vagga
    description: Kewaspadaan
    parent: /appamada_vagga
  jara_vagga:
    output: true
    title: Bab XI - Jara Vagga
    description: Usia Tua
    parent: /jara_vagga